# Generated by Django 3.2.3 on 2021-05-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=300)),
                ('hours', models.IntegerField(max_length=10)),
            ],
        ),
    ]
