# Generated by Django 3.2.3 on 2021-05-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
